EEEEEEEE
======================================================================
ERROR: test_create_event_today (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 146, in test_create_event_today
    create_event(driver, time, date, name, desc, tags, guests)
  File "integration_test/test.py", line 29, in create_event
    driver.find_element_by_link_text("Add event").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add event"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_event_tomorrow (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 173, in test_create_event_tomorrow
    create_event(driver, time, date, name, desc, tags, guests)
  File "integration_test/test.py", line 29, in create_event
    driver.find_element_by_link_text("Add event").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add event"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_note_today (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 236, in test_create_note_today
    create_note(driver, date, name, desc, tags)
  File "integration_test/test.py", line 73, in create_note
    driver.find_element_by_link_text("Add note").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add note"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_note_tomorrow (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 253, in test_create_note_tomorrow
    create_note(driver, date, name, desc, tags)
  File "integration_test/test.py", line 73, in create_note
    driver.find_element_by_link_text("Add note").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add note"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_reminder_earlier (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 222, in test_create_reminder_earlier
    create_reminder(driver, time, date, text)
  File "integration_test/test.py", line 58, in create_reminder
    driver.find_element_by_link_text("Add reminder").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add reminder"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_reminder_today (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 196, in test_create_reminder_today
    create_reminder(driver, time, date, text)
  File "integration_test/test.py", line 58, in create_reminder
    driver.find_element_by_link_text("Add reminder").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add reminder"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_reminder_tomorrow (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 209, in test_create_reminder_tomorrow
    create_reminder(driver, time, date, text)
  File "integration_test/test.py", line 58, in create_reminder
    driver.find_element_by_link_text("Add reminder").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add reminder"}
  (Session info: headless chrome=89.0.4389.114)


======================================================================
ERROR: test_create_task_one_day (__main__.CalendarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_test/test.py", line 278, in test_create_task_one_day
    create_task(self.driver, date, **params)
  File "integration_test/test.py", line 95, in create_task
    driver.find_element_by_link_text("Add task").click()
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jacek/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Add task"}
  (Session info: headless chrome=89.0.4389.114)


----------------------------------------------------------------------
Ran 8 tests in 49.000s

FAILED (errors=8)
